testing_mode = true
payment_provider = "stripe" #bmac if using Buy Me A Coffee
stripe_api_key_test = "sk_test_..." #only needed if using Stripe
stripe_api_key = "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" #only needed if using Stripe
stripe_link = "https://buy.stripe.com/dR6bLU1Zh2hGg0gbII" #only needed if using Stripe
stripe_link_test = "https://buy.stripe.com/test_..." #only needed if using Stripe
client_id = "244293800189-2mojav0mktaot7jrbc950gqqf5hra1pv.apps.googleusercontent.com"
client_secret = "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"
redirect_url_test = 'http://localhost:8501/'
redirect_url = "https://ltzbld.streamlit.app"